
export const skillsImage = (skill) => {
    const skillID = skill.toLowerCase();
    const basePath = '/svg/skills/';
    
    const skillMap = {
      'gcp': 'gcp.svg',
      'html': 'html.svg',
      'photoshop': 'photoshop.svg',
      'docker': 'docker.svg',
      'illustrator': 'illustrator.svg',
      'adobe xd': 'adobe-xd.svg',
      'after effects': 'after-effects.svg',
      'css': 'css.svg',
      'angular': 'angular.svg',
      'javascript': 'javascript.svg',
      'next js': 'nextJS.svg',
      'nuxt js': 'nuxtJS.svg',
      'react': 'react.svg',
      'svelte': 'svelte.svg',
      'typescript': 'typescript.svg',
      'vue': 'vue.svg',
      'bootstrap': 'bootstrap.svg',
      'bulma': 'bulma.svg',
      'capacitorjs': 'capacitorjs.svg',
      'coffeescript': 'coffeescript.svg',
      'memsql': 'memsql.svg',
      'mongodb': 'mongoDB.svg',
      'mysql': 'mysql.svg',
      'postgresql': 'postgresql.svg',
      'tailwind': 'tailwind.svg',
      'vitejs': 'vitejs.svg',
      'vuetifyjs': 'vuetifyjs.svg',
      'c': 'c.svg',
      'c++': 'cplusplus.svg',
      'c#': 'csharp.svg',
      'dart': 'dart.svg',
      'go': 'go.svg',
      'java': 'java.svg',
      'kotlin': 'kotlin.svg',
      'julia': 'julia.svg',
      'matlab': 'matlab.svg',
      'php': 'php.svg',
      'python': 'python.svg',
      'ruby': 'ruby.svg',
      'swift': 'swift.svg',
      'adobe audition': 'adobeaudition.svg',
      'aws': 'aws.svg',
      'deno': 'deno.svg',
      'django': 'django.svg',
      'firebase': 'firebase.svg',
      'gimp': 'gimp.svg',
      'git': 'git.svg',
      'graphql': 'graphql.svg',
      'lightroom': 'lightroom.svg',
      'materialui': 'materialui.svg',
      'nginx': 'nginx.svg',
      'numpy': 'numpy.svg',
      'opencv': 'opencv.svg',
      'premiere pro': 'premierepro.svg',
      'pytorch': 'pytorch.svg',
      'selenium': 'selenium.svg',
      'strapi': 'strapi.svg',
      'tensorflow': 'tensorflow.svg',
      'webix': 'webix.svg',
      'wordpress': 'wordpress.svg',
      'azure': 'azure.svg',
      'blender': 'blender.svg',
      'fastify': 'fastify.svg',
      'figma': 'figma.svg',
      'flutter': 'flutter.svg',
      'haxe': 'haxe.svg',
      'ionic': 'ionic.svg',
      'markdown': 'markdown.svg',
      'microsoft office': 'microsoftoffice.svg',
      'picsart': 'picsart.svg',
      'sketch': 'sketch.svg',
      'unity': 'unity.svg',
      'wolframalpha': 'wolframalpha.svg',
      'canva': 'canva.svg'
    };
    
    if (skillMap[skillID]) {
      return basePath + skillMap[skillID];
    }
    
    return null;
  }